// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="example_example,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=176,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=2087,HLS_SYN_LUT=3826,HLS_VERSION=2022_1}" *)

module example (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_a_AWVALID,
        m_axi_a_AWREADY,
        m_axi_a_AWADDR,
        m_axi_a_AWID,
        m_axi_a_AWLEN,
        m_axi_a_AWSIZE,
        m_axi_a_AWBURST,
        m_axi_a_AWLOCK,
        m_axi_a_AWCACHE,
        m_axi_a_AWPROT,
        m_axi_a_AWQOS,
        m_axi_a_AWREGION,
        m_axi_a_AWUSER,
        m_axi_a_WVALID,
        m_axi_a_WREADY,
        m_axi_a_WDATA,
        m_axi_a_WSTRB,
        m_axi_a_WLAST,
        m_axi_a_WID,
        m_axi_a_WUSER,
        m_axi_a_ARVALID,
        m_axi_a_ARREADY,
        m_axi_a_ARADDR,
        m_axi_a_ARID,
        m_axi_a_ARLEN,
        m_axi_a_ARSIZE,
        m_axi_a_ARBURST,
        m_axi_a_ARLOCK,
        m_axi_a_ARCACHE,
        m_axi_a_ARPROT,
        m_axi_a_ARQOS,
        m_axi_a_ARREGION,
        m_axi_a_ARUSER,
        m_axi_a_RVALID,
        m_axi_a_RREADY,
        m_axi_a_RDATA,
        m_axi_a_RLAST,
        m_axi_a_RID,
        m_axi_a_RUSER,
        m_axi_a_RRESP,
        m_axi_a_BVALID,
        m_axi_a_BREADY,
        m_axi_a_BRESP,
        m_axi_a_BID,
        m_axi_a_BUSER,
        m_axi_b_AWVALID,
        m_axi_b_AWREADY,
        m_axi_b_AWADDR,
        m_axi_b_AWID,
        m_axi_b_AWLEN,
        m_axi_b_AWSIZE,
        m_axi_b_AWBURST,
        m_axi_b_AWLOCK,
        m_axi_b_AWCACHE,
        m_axi_b_AWPROT,
        m_axi_b_AWQOS,
        m_axi_b_AWREGION,
        m_axi_b_AWUSER,
        m_axi_b_WVALID,
        m_axi_b_WREADY,
        m_axi_b_WDATA,
        m_axi_b_WSTRB,
        m_axi_b_WLAST,
        m_axi_b_WID,
        m_axi_b_WUSER,
        m_axi_b_ARVALID,
        m_axi_b_ARREADY,
        m_axi_b_ARADDR,
        m_axi_b_ARID,
        m_axi_b_ARLEN,
        m_axi_b_ARSIZE,
        m_axi_b_ARBURST,
        m_axi_b_ARLOCK,
        m_axi_b_ARCACHE,
        m_axi_b_ARPROT,
        m_axi_b_ARQOS,
        m_axi_b_ARREGION,
        m_axi_b_ARUSER,
        m_axi_b_RVALID,
        m_axi_b_RREADY,
        m_axi_b_RDATA,
        m_axi_b_RLAST,
        m_axi_b_RID,
        m_axi_b_RUSER,
        m_axi_b_RRESP,
        m_axi_b_BVALID,
        m_axi_b_BREADY,
        m_axi_b_BRESP,
        m_axi_b_BID,
        m_axi_b_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_A_ID_WIDTH = 1;
parameter    C_M_AXI_A_ADDR_WIDTH = 64;
parameter    C_M_AXI_A_DATA_WIDTH = 32;
parameter    C_M_AXI_A_AWUSER_WIDTH = 1;
parameter    C_M_AXI_A_ARUSER_WIDTH = 1;
parameter    C_M_AXI_A_WUSER_WIDTH = 1;
parameter    C_M_AXI_A_RUSER_WIDTH = 1;
parameter    C_M_AXI_A_BUSER_WIDTH = 1;
parameter    C_M_AXI_A_USER_VALUE = 0;
parameter    C_M_AXI_A_PROT_VALUE = 0;
parameter    C_M_AXI_A_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_B_ID_WIDTH = 1;
parameter    C_M_AXI_B_ADDR_WIDTH = 64;
parameter    C_M_AXI_B_DATA_WIDTH = 32;
parameter    C_M_AXI_B_AWUSER_WIDTH = 1;
parameter    C_M_AXI_B_ARUSER_WIDTH = 1;
parameter    C_M_AXI_B_WUSER_WIDTH = 1;
parameter    C_M_AXI_B_RUSER_WIDTH = 1;
parameter    C_M_AXI_B_BUSER_WIDTH = 1;
parameter    C_M_AXI_B_USER_VALUE = 0;
parameter    C_M_AXI_B_PROT_VALUE = 0;
parameter    C_M_AXI_B_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_A_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_B_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_a_AWVALID;
input   m_axi_a_AWREADY;
output  [C_M_AXI_A_ADDR_WIDTH - 1:0] m_axi_a_AWADDR;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_AWID;
output  [7:0] m_axi_a_AWLEN;
output  [2:0] m_axi_a_AWSIZE;
output  [1:0] m_axi_a_AWBURST;
output  [1:0] m_axi_a_AWLOCK;
output  [3:0] m_axi_a_AWCACHE;
output  [2:0] m_axi_a_AWPROT;
output  [3:0] m_axi_a_AWQOS;
output  [3:0] m_axi_a_AWREGION;
output  [C_M_AXI_A_AWUSER_WIDTH - 1:0] m_axi_a_AWUSER;
output   m_axi_a_WVALID;
input   m_axi_a_WREADY;
output  [C_M_AXI_A_DATA_WIDTH - 1:0] m_axi_a_WDATA;
output  [C_M_AXI_A_WSTRB_WIDTH - 1:0] m_axi_a_WSTRB;
output   m_axi_a_WLAST;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_WID;
output  [C_M_AXI_A_WUSER_WIDTH - 1:0] m_axi_a_WUSER;
output   m_axi_a_ARVALID;
input   m_axi_a_ARREADY;
output  [C_M_AXI_A_ADDR_WIDTH - 1:0] m_axi_a_ARADDR;
output  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_ARID;
output  [7:0] m_axi_a_ARLEN;
output  [2:0] m_axi_a_ARSIZE;
output  [1:0] m_axi_a_ARBURST;
output  [1:0] m_axi_a_ARLOCK;
output  [3:0] m_axi_a_ARCACHE;
output  [2:0] m_axi_a_ARPROT;
output  [3:0] m_axi_a_ARQOS;
output  [3:0] m_axi_a_ARREGION;
output  [C_M_AXI_A_ARUSER_WIDTH - 1:0] m_axi_a_ARUSER;
input   m_axi_a_RVALID;
output   m_axi_a_RREADY;
input  [C_M_AXI_A_DATA_WIDTH - 1:0] m_axi_a_RDATA;
input   m_axi_a_RLAST;
input  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_RID;
input  [C_M_AXI_A_RUSER_WIDTH - 1:0] m_axi_a_RUSER;
input  [1:0] m_axi_a_RRESP;
input   m_axi_a_BVALID;
output   m_axi_a_BREADY;
input  [1:0] m_axi_a_BRESP;
input  [C_M_AXI_A_ID_WIDTH - 1:0] m_axi_a_BID;
input  [C_M_AXI_A_BUSER_WIDTH - 1:0] m_axi_a_BUSER;
output   m_axi_b_AWVALID;
input   m_axi_b_AWREADY;
output  [C_M_AXI_B_ADDR_WIDTH - 1:0] m_axi_b_AWADDR;
output  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_AWID;
output  [7:0] m_axi_b_AWLEN;
output  [2:0] m_axi_b_AWSIZE;
output  [1:0] m_axi_b_AWBURST;
output  [1:0] m_axi_b_AWLOCK;
output  [3:0] m_axi_b_AWCACHE;
output  [2:0] m_axi_b_AWPROT;
output  [3:0] m_axi_b_AWQOS;
output  [3:0] m_axi_b_AWREGION;
output  [C_M_AXI_B_AWUSER_WIDTH - 1:0] m_axi_b_AWUSER;
output   m_axi_b_WVALID;
input   m_axi_b_WREADY;
output  [C_M_AXI_B_DATA_WIDTH - 1:0] m_axi_b_WDATA;
output  [C_M_AXI_B_WSTRB_WIDTH - 1:0] m_axi_b_WSTRB;
output   m_axi_b_WLAST;
output  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_WID;
output  [C_M_AXI_B_WUSER_WIDTH - 1:0] m_axi_b_WUSER;
output   m_axi_b_ARVALID;
input   m_axi_b_ARREADY;
output  [C_M_AXI_B_ADDR_WIDTH - 1:0] m_axi_b_ARADDR;
output  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_ARID;
output  [7:0] m_axi_b_ARLEN;
output  [2:0] m_axi_b_ARSIZE;
output  [1:0] m_axi_b_ARBURST;
output  [1:0] m_axi_b_ARLOCK;
output  [3:0] m_axi_b_ARCACHE;
output  [2:0] m_axi_b_ARPROT;
output  [3:0] m_axi_b_ARQOS;
output  [3:0] m_axi_b_ARREGION;
output  [C_M_AXI_B_ARUSER_WIDTH - 1:0] m_axi_b_ARUSER;
input   m_axi_b_RVALID;
output   m_axi_b_RREADY;
input  [C_M_AXI_B_DATA_WIDTH - 1:0] m_axi_b_RDATA;
input   m_axi_b_RLAST;
input  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_RID;
input  [C_M_AXI_B_RUSER_WIDTH - 1:0] m_axi_b_RUSER;
input  [1:0] m_axi_b_RRESP;
input   m_axi_b_BVALID;
output   m_axi_b_BREADY;
input  [1:0] m_axi_b_BRESP;
input  [C_M_AXI_B_ID_WIDTH - 1:0] m_axi_b_BID;
input  [C_M_AXI_B_BUSER_WIDTH - 1:0] m_axi_b_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] a_offset;
wire   [63:0] b_offset;
reg    a_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    a_blk_n_AW;
wire    ap_CS_fsm_state11;
reg    a_blk_n_B;
wire    ap_CS_fsm_state19;
reg    b_blk_n_AR;
reg    b_blk_n_AW;
reg    b_blk_n_B;
reg   [61:0] trunc_ln_reg_188;
reg   [61:0] trunc_ln1_reg_195;
reg   [63:0] a_addr_reg_202;
reg   [63:0] b_addr_reg_207;
reg   [5:0] buffa_address0;
reg    buffa_ce0;
reg    buffa_we0;
reg   [31:0] buffa_d0;
wire   [31:0] buffa_q0;
reg    buffa_ce1;
wire   [31:0] buffa_q1;
reg   [5:0] buffb_address0;
reg    buffb_ce0;
reg    buffb_we0;
reg   [31:0] buffb_d0;
wire   [31:0] buffb_q0;
reg    buffb_ce1;
wire   [31:0] buffb_q1;
wire    grp_example_Pipeline_1_fu_110_ap_start;
wire    grp_example_Pipeline_1_fu_110_ap_done;
wire    grp_example_Pipeline_1_fu_110_ap_idle;
wire    grp_example_Pipeline_1_fu_110_ap_ready;
wire    grp_example_Pipeline_1_fu_110_m_axi_a_AWVALID;
wire   [63:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWADDR;
wire   [0:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWID;
wire   [31:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWLEN;
wire   [2:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWSIZE;
wire   [1:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWBURST;
wire   [1:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWLOCK;
wire   [3:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWCACHE;
wire   [2:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWPROT;
wire   [3:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWQOS;
wire   [3:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWREGION;
wire   [0:0] grp_example_Pipeline_1_fu_110_m_axi_a_AWUSER;
wire    grp_example_Pipeline_1_fu_110_m_axi_a_WVALID;
wire   [31:0] grp_example_Pipeline_1_fu_110_m_axi_a_WDATA;
wire   [3:0] grp_example_Pipeline_1_fu_110_m_axi_a_WSTRB;
wire    grp_example_Pipeline_1_fu_110_m_axi_a_WLAST;
wire   [0:0] grp_example_Pipeline_1_fu_110_m_axi_a_WID;
wire   [0:0] grp_example_Pipeline_1_fu_110_m_axi_a_WUSER;
wire    grp_example_Pipeline_1_fu_110_m_axi_a_ARVALID;
wire   [63:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARADDR;
wire   [0:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARID;
wire   [31:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARLEN;
wire   [2:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARSIZE;
wire   [1:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARBURST;
wire   [1:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARLOCK;
wire   [3:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARCACHE;
wire   [2:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARPROT;
wire   [3:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARQOS;
wire   [3:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARREGION;
wire   [0:0] grp_example_Pipeline_1_fu_110_m_axi_a_ARUSER;
wire    grp_example_Pipeline_1_fu_110_m_axi_a_RREADY;
wire    grp_example_Pipeline_1_fu_110_m_axi_a_BREADY;
wire   [5:0] grp_example_Pipeline_1_fu_110_buffa_address0;
wire    grp_example_Pipeline_1_fu_110_buffa_ce0;
wire    grp_example_Pipeline_1_fu_110_buffa_we0;
wire   [31:0] grp_example_Pipeline_1_fu_110_buffa_d0;
wire    grp_example_Pipeline_2_fu_118_ap_start;
wire    grp_example_Pipeline_2_fu_118_ap_done;
wire    grp_example_Pipeline_2_fu_118_ap_idle;
wire    grp_example_Pipeline_2_fu_118_ap_ready;
wire    grp_example_Pipeline_2_fu_118_m_axi_b_AWVALID;
wire   [63:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWADDR;
wire   [0:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWID;
wire   [31:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWLEN;
wire   [2:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWSIZE;
wire   [1:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWBURST;
wire   [1:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWLOCK;
wire   [3:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWCACHE;
wire   [2:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWPROT;
wire   [3:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWQOS;
wire   [3:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWREGION;
wire   [0:0] grp_example_Pipeline_2_fu_118_m_axi_b_AWUSER;
wire    grp_example_Pipeline_2_fu_118_m_axi_b_WVALID;
wire   [31:0] grp_example_Pipeline_2_fu_118_m_axi_b_WDATA;
wire   [3:0] grp_example_Pipeline_2_fu_118_m_axi_b_WSTRB;
wire    grp_example_Pipeline_2_fu_118_m_axi_b_WLAST;
wire   [0:0] grp_example_Pipeline_2_fu_118_m_axi_b_WID;
wire   [0:0] grp_example_Pipeline_2_fu_118_m_axi_b_WUSER;
wire    grp_example_Pipeline_2_fu_118_m_axi_b_ARVALID;
wire   [63:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARADDR;
wire   [0:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARID;
wire   [31:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARLEN;
wire   [2:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARSIZE;
wire   [1:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARBURST;
wire   [1:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARLOCK;
wire   [3:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARCACHE;
wire   [2:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARPROT;
wire   [3:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARQOS;
wire   [3:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARREGION;
wire   [0:0] grp_example_Pipeline_2_fu_118_m_axi_b_ARUSER;
wire    grp_example_Pipeline_2_fu_118_m_axi_b_RREADY;
wire    grp_example_Pipeline_2_fu_118_m_axi_b_BREADY;
wire   [5:0] grp_example_Pipeline_2_fu_118_buffb_address0;
wire    grp_example_Pipeline_2_fu_118_buffb_ce0;
wire    grp_example_Pipeline_2_fu_118_buffb_we0;
wire   [31:0] grp_example_Pipeline_2_fu_118_buffb_d0;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_done;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_idle;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_ready;
wire   [5:0] grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_address0;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_ce0;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_we0;
wire   [31:0] grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_d0;
wire   [5:0] grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_address1;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_ce1;
wire   [5:0] grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_address0;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_ce0;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_we0;
wire   [31:0] grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_d0;
wire   [5:0] grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_address1;
wire    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_ce1;
wire    grp_example_Pipeline_4_fu_132_ap_start;
wire    grp_example_Pipeline_4_fu_132_ap_done;
wire    grp_example_Pipeline_4_fu_132_ap_idle;
wire    grp_example_Pipeline_4_fu_132_ap_ready;
wire    grp_example_Pipeline_4_fu_132_m_axi_a_AWVALID;
wire   [63:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWADDR;
wire   [0:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWID;
wire   [31:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWLEN;
wire   [2:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWSIZE;
wire   [1:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWBURST;
wire   [1:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWLOCK;
wire   [3:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWCACHE;
wire   [2:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWPROT;
wire   [3:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWQOS;
wire   [3:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWREGION;
wire   [0:0] grp_example_Pipeline_4_fu_132_m_axi_a_AWUSER;
wire    grp_example_Pipeline_4_fu_132_m_axi_a_WVALID;
wire   [31:0] grp_example_Pipeline_4_fu_132_m_axi_a_WDATA;
wire   [3:0] grp_example_Pipeline_4_fu_132_m_axi_a_WSTRB;
wire    grp_example_Pipeline_4_fu_132_m_axi_a_WLAST;
wire   [0:0] grp_example_Pipeline_4_fu_132_m_axi_a_WID;
wire   [0:0] grp_example_Pipeline_4_fu_132_m_axi_a_WUSER;
wire    grp_example_Pipeline_4_fu_132_m_axi_a_ARVALID;
wire   [63:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARADDR;
wire   [0:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARID;
wire   [31:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARLEN;
wire   [2:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARSIZE;
wire   [1:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARBURST;
wire   [1:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARLOCK;
wire   [3:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARCACHE;
wire   [2:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARPROT;
wire   [3:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARQOS;
wire   [3:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARREGION;
wire   [0:0] grp_example_Pipeline_4_fu_132_m_axi_a_ARUSER;
wire    grp_example_Pipeline_4_fu_132_m_axi_a_RREADY;
wire    grp_example_Pipeline_4_fu_132_m_axi_a_BREADY;
wire   [5:0] grp_example_Pipeline_4_fu_132_buffa_address0;
wire    grp_example_Pipeline_4_fu_132_buffa_ce0;
wire    grp_example_Pipeline_5_fu_140_ap_start;
wire    grp_example_Pipeline_5_fu_140_ap_done;
wire    grp_example_Pipeline_5_fu_140_ap_idle;
wire    grp_example_Pipeline_5_fu_140_ap_ready;
wire    grp_example_Pipeline_5_fu_140_m_axi_b_AWVALID;
wire   [63:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWADDR;
wire   [0:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWID;
wire   [31:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWLEN;
wire   [2:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWSIZE;
wire   [1:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWBURST;
wire   [1:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWLOCK;
wire   [3:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWCACHE;
wire   [2:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWPROT;
wire   [3:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWQOS;
wire   [3:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWREGION;
wire   [0:0] grp_example_Pipeline_5_fu_140_m_axi_b_AWUSER;
wire    grp_example_Pipeline_5_fu_140_m_axi_b_WVALID;
wire   [31:0] grp_example_Pipeline_5_fu_140_m_axi_b_WDATA;
wire   [3:0] grp_example_Pipeline_5_fu_140_m_axi_b_WSTRB;
wire    grp_example_Pipeline_5_fu_140_m_axi_b_WLAST;
wire   [0:0] grp_example_Pipeline_5_fu_140_m_axi_b_WID;
wire   [0:0] grp_example_Pipeline_5_fu_140_m_axi_b_WUSER;
wire    grp_example_Pipeline_5_fu_140_m_axi_b_ARVALID;
wire   [63:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARADDR;
wire   [0:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARID;
wire   [31:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARLEN;
wire   [2:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARSIZE;
wire   [1:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARBURST;
wire   [1:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARLOCK;
wire   [3:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARCACHE;
wire   [2:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARPROT;
wire   [3:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARQOS;
wire   [3:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARREGION;
wire   [0:0] grp_example_Pipeline_5_fu_140_m_axi_b_ARUSER;
wire    grp_example_Pipeline_5_fu_140_m_axi_b_RREADY;
wire    grp_example_Pipeline_5_fu_140_m_axi_b_BREADY;
wire   [5:0] grp_example_Pipeline_5_fu_140_buffb_address0;
wire    grp_example_Pipeline_5_fu_140_buffb_ce0;
reg    a_AWVALID;
wire    a_AWREADY;
reg   [63:0] a_AWADDR;
reg   [31:0] a_AWLEN;
reg    a_WVALID;
wire    a_WREADY;
reg    a_ARVALID;
wire    a_ARREADY;
reg   [63:0] a_ARADDR;
reg   [31:0] a_ARLEN;
wire    a_RVALID;
reg    a_RREADY;
wire   [31:0] a_RDATA;
wire   [8:0] a_RFIFONUM;
wire    a_BVALID;
reg    a_BREADY;
reg    b_AWVALID;
wire    b_AWREADY;
reg   [63:0] b_AWADDR;
reg   [31:0] b_AWLEN;
reg    b_WVALID;
wire    b_WREADY;
reg    b_ARVALID;
wire    b_ARREADY;
reg   [63:0] b_ARADDR;
reg   [31:0] b_ARLEN;
wire    b_RVALID;
reg    b_RREADY;
wire   [31:0] b_RDATA;
wire   [8:0] b_RFIFONUM;
wire    b_BVALID;
reg    b_BREADY;
reg    grp_example_Pipeline_1_fu_110_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_example_Pipeline_2_fu_118_ap_start_reg;
reg    grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start_reg;
reg    ap_block_state11_io;
wire    ap_CS_fsm_state12;
reg    grp_example_Pipeline_4_fu_132_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_example_Pipeline_5_fu_140_ap_start_reg;
wire  signed [63:0] sext_ln44_fu_168_p1;
wire  signed [63:0] sext_ln48_fu_178_p1;
reg    ap_block_state2_io;
reg    ap_block_state19;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_block_state10_on_subcall_done;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_block_state14_on_subcall_done;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 grp_example_Pipeline_1_fu_110_ap_start_reg = 1'b0;
#0 grp_example_Pipeline_2_fu_118_ap_start_reg = 1'b0;
#0 grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start_reg = 1'b0;
#0 grp_example_Pipeline_4_fu_132_ap_start_reg = 1'b0;
#0 grp_example_Pipeline_5_fu_140_ap_start_reg = 1'b0;
end

example_buffa_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
buffa_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffa_address0),
    .ce0(buffa_ce0),
    .we0(buffa_we0),
    .d0(buffa_d0),
    .q0(buffa_q0),
    .address1(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_address1),
    .ce1(buffa_ce1),
    .q1(buffa_q1)
);

example_buffa_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
buffb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buffb_address0),
    .ce0(buffb_ce0),
    .we0(buffb_we0),
    .d0(buffb_d0),
    .q0(buffb_q0),
    .address1(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_address1),
    .ce1(buffb_ce1),
    .q1(buffb_q1)
);

example_example_Pipeline_1 grp_example_Pipeline_1_fu_110(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_example_Pipeline_1_fu_110_ap_start),
    .ap_done(grp_example_Pipeline_1_fu_110_ap_done),
    .ap_idle(grp_example_Pipeline_1_fu_110_ap_idle),
    .ap_ready(grp_example_Pipeline_1_fu_110_ap_ready),
    .m_axi_a_AWVALID(grp_example_Pipeline_1_fu_110_m_axi_a_AWVALID),
    .m_axi_a_AWREADY(1'b0),
    .m_axi_a_AWADDR(grp_example_Pipeline_1_fu_110_m_axi_a_AWADDR),
    .m_axi_a_AWID(grp_example_Pipeline_1_fu_110_m_axi_a_AWID),
    .m_axi_a_AWLEN(grp_example_Pipeline_1_fu_110_m_axi_a_AWLEN),
    .m_axi_a_AWSIZE(grp_example_Pipeline_1_fu_110_m_axi_a_AWSIZE),
    .m_axi_a_AWBURST(grp_example_Pipeline_1_fu_110_m_axi_a_AWBURST),
    .m_axi_a_AWLOCK(grp_example_Pipeline_1_fu_110_m_axi_a_AWLOCK),
    .m_axi_a_AWCACHE(grp_example_Pipeline_1_fu_110_m_axi_a_AWCACHE),
    .m_axi_a_AWPROT(grp_example_Pipeline_1_fu_110_m_axi_a_AWPROT),
    .m_axi_a_AWQOS(grp_example_Pipeline_1_fu_110_m_axi_a_AWQOS),
    .m_axi_a_AWREGION(grp_example_Pipeline_1_fu_110_m_axi_a_AWREGION),
    .m_axi_a_AWUSER(grp_example_Pipeline_1_fu_110_m_axi_a_AWUSER),
    .m_axi_a_WVALID(grp_example_Pipeline_1_fu_110_m_axi_a_WVALID),
    .m_axi_a_WREADY(1'b0),
    .m_axi_a_WDATA(grp_example_Pipeline_1_fu_110_m_axi_a_WDATA),
    .m_axi_a_WSTRB(grp_example_Pipeline_1_fu_110_m_axi_a_WSTRB),
    .m_axi_a_WLAST(grp_example_Pipeline_1_fu_110_m_axi_a_WLAST),
    .m_axi_a_WID(grp_example_Pipeline_1_fu_110_m_axi_a_WID),
    .m_axi_a_WUSER(grp_example_Pipeline_1_fu_110_m_axi_a_WUSER),
    .m_axi_a_ARVALID(grp_example_Pipeline_1_fu_110_m_axi_a_ARVALID),
    .m_axi_a_ARREADY(a_ARREADY),
    .m_axi_a_ARADDR(grp_example_Pipeline_1_fu_110_m_axi_a_ARADDR),
    .m_axi_a_ARID(grp_example_Pipeline_1_fu_110_m_axi_a_ARID),
    .m_axi_a_ARLEN(grp_example_Pipeline_1_fu_110_m_axi_a_ARLEN),
    .m_axi_a_ARSIZE(grp_example_Pipeline_1_fu_110_m_axi_a_ARSIZE),
    .m_axi_a_ARBURST(grp_example_Pipeline_1_fu_110_m_axi_a_ARBURST),
    .m_axi_a_ARLOCK(grp_example_Pipeline_1_fu_110_m_axi_a_ARLOCK),
    .m_axi_a_ARCACHE(grp_example_Pipeline_1_fu_110_m_axi_a_ARCACHE),
    .m_axi_a_ARPROT(grp_example_Pipeline_1_fu_110_m_axi_a_ARPROT),
    .m_axi_a_ARQOS(grp_example_Pipeline_1_fu_110_m_axi_a_ARQOS),
    .m_axi_a_ARREGION(grp_example_Pipeline_1_fu_110_m_axi_a_ARREGION),
    .m_axi_a_ARUSER(grp_example_Pipeline_1_fu_110_m_axi_a_ARUSER),
    .m_axi_a_RVALID(a_RVALID),
    .m_axi_a_RREADY(grp_example_Pipeline_1_fu_110_m_axi_a_RREADY),
    .m_axi_a_RDATA(a_RDATA),
    .m_axi_a_RLAST(1'b0),
    .m_axi_a_RID(1'd0),
    .m_axi_a_RFIFONUM(a_RFIFONUM),
    .m_axi_a_RUSER(1'd0),
    .m_axi_a_RRESP(2'd0),
    .m_axi_a_BVALID(1'b0),
    .m_axi_a_BREADY(grp_example_Pipeline_1_fu_110_m_axi_a_BREADY),
    .m_axi_a_BRESP(2'd0),
    .m_axi_a_BID(1'd0),
    .m_axi_a_BUSER(1'd0),
    .sext_ln44(trunc_ln_reg_188),
    .buffa_address0(grp_example_Pipeline_1_fu_110_buffa_address0),
    .buffa_ce0(grp_example_Pipeline_1_fu_110_buffa_ce0),
    .buffa_we0(grp_example_Pipeline_1_fu_110_buffa_we0),
    .buffa_d0(grp_example_Pipeline_1_fu_110_buffa_d0)
);

example_example_Pipeline_2 grp_example_Pipeline_2_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_example_Pipeline_2_fu_118_ap_start),
    .ap_done(grp_example_Pipeline_2_fu_118_ap_done),
    .ap_idle(grp_example_Pipeline_2_fu_118_ap_idle),
    .ap_ready(grp_example_Pipeline_2_fu_118_ap_ready),
    .m_axi_b_AWVALID(grp_example_Pipeline_2_fu_118_m_axi_b_AWVALID),
    .m_axi_b_AWREADY(1'b0),
    .m_axi_b_AWADDR(grp_example_Pipeline_2_fu_118_m_axi_b_AWADDR),
    .m_axi_b_AWID(grp_example_Pipeline_2_fu_118_m_axi_b_AWID),
    .m_axi_b_AWLEN(grp_example_Pipeline_2_fu_118_m_axi_b_AWLEN),
    .m_axi_b_AWSIZE(grp_example_Pipeline_2_fu_118_m_axi_b_AWSIZE),
    .m_axi_b_AWBURST(grp_example_Pipeline_2_fu_118_m_axi_b_AWBURST),
    .m_axi_b_AWLOCK(grp_example_Pipeline_2_fu_118_m_axi_b_AWLOCK),
    .m_axi_b_AWCACHE(grp_example_Pipeline_2_fu_118_m_axi_b_AWCACHE),
    .m_axi_b_AWPROT(grp_example_Pipeline_2_fu_118_m_axi_b_AWPROT),
    .m_axi_b_AWQOS(grp_example_Pipeline_2_fu_118_m_axi_b_AWQOS),
    .m_axi_b_AWREGION(grp_example_Pipeline_2_fu_118_m_axi_b_AWREGION),
    .m_axi_b_AWUSER(grp_example_Pipeline_2_fu_118_m_axi_b_AWUSER),
    .m_axi_b_WVALID(grp_example_Pipeline_2_fu_118_m_axi_b_WVALID),
    .m_axi_b_WREADY(1'b0),
    .m_axi_b_WDATA(grp_example_Pipeline_2_fu_118_m_axi_b_WDATA),
    .m_axi_b_WSTRB(grp_example_Pipeline_2_fu_118_m_axi_b_WSTRB),
    .m_axi_b_WLAST(grp_example_Pipeline_2_fu_118_m_axi_b_WLAST),
    .m_axi_b_WID(grp_example_Pipeline_2_fu_118_m_axi_b_WID),
    .m_axi_b_WUSER(grp_example_Pipeline_2_fu_118_m_axi_b_WUSER),
    .m_axi_b_ARVALID(grp_example_Pipeline_2_fu_118_m_axi_b_ARVALID),
    .m_axi_b_ARREADY(b_ARREADY),
    .m_axi_b_ARADDR(grp_example_Pipeline_2_fu_118_m_axi_b_ARADDR),
    .m_axi_b_ARID(grp_example_Pipeline_2_fu_118_m_axi_b_ARID),
    .m_axi_b_ARLEN(grp_example_Pipeline_2_fu_118_m_axi_b_ARLEN),
    .m_axi_b_ARSIZE(grp_example_Pipeline_2_fu_118_m_axi_b_ARSIZE),
    .m_axi_b_ARBURST(grp_example_Pipeline_2_fu_118_m_axi_b_ARBURST),
    .m_axi_b_ARLOCK(grp_example_Pipeline_2_fu_118_m_axi_b_ARLOCK),
    .m_axi_b_ARCACHE(grp_example_Pipeline_2_fu_118_m_axi_b_ARCACHE),
    .m_axi_b_ARPROT(grp_example_Pipeline_2_fu_118_m_axi_b_ARPROT),
    .m_axi_b_ARQOS(grp_example_Pipeline_2_fu_118_m_axi_b_ARQOS),
    .m_axi_b_ARREGION(grp_example_Pipeline_2_fu_118_m_axi_b_ARREGION),
    .m_axi_b_ARUSER(grp_example_Pipeline_2_fu_118_m_axi_b_ARUSER),
    .m_axi_b_RVALID(rvalid),
    .m_axi_b_RREADY(grp_example_Pipeline_2_fu_118_m_axi_b_RREADY),
    .m_axi_b_RDATA(b_RDATA),
    .m_axi_b_RLAST(1'b0),
    .m_axi_b_RID(1'd0),
    .m_axi_b_RFIFONUM(b_RFIFONUM),
    .m_axi_b_RUSER(1'd0),
    .m_axi_b_RRESP(2'd0),
    .m_axi_b_BVALID(1'b0),
    .m_axi_b_BREADY(grp_example_Pipeline_2_fu_118_m_axi_b_BREADY),
    .m_axi_b_BRESP(2'd0),
    .m_axi_b_BID(1'd0),
    .m_axi_b_BUSER(1'd0),
    .sext_ln48(trunc_ln1_reg_195),
    .buffb_address0(grp_example_Pipeline_2_fu_118_buffb_address0),
    .buffb_ce0(grp_example_Pipeline_2_fu_118_buffb_ce0),
    .buffb_we0(grp_example_Pipeline_2_fu_118_buffb_we0),
    .buffb_d0(grp_example_Pipeline_2_fu_118_buffb_d0)
);
wire rvalid;

assign rvalid=1'b1;

example_example_Pipeline_VITIS_LOOP_57_1 grp_example_Pipeline_VITIS_LOOP_57_1_fu_126(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start),
    .ap_done(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_done),
    .ap_idle(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_idle),
    .ap_ready(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_ready),
    .buffa_address0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_address0),
    .buffa_ce0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_ce0),
    .buffa_we0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_we0),
    .buffa_d0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_d0),
    .buffa_address1(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_address1),
    .buffa_ce1(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_ce1),
    .buffa_q1(buffa_q1),
    .buffb_address0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_address0),
    .buffb_ce0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_ce0),
    .buffb_we0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_we0),
    .buffb_d0(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_d0),
    .buffb_address1(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_address1),
    .buffb_ce1(grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_ce1),
    .buffb_q1(buffb_q1)
);

example_example_Pipeline_4 grp_example_Pipeline_4_fu_132(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_example_Pipeline_4_fu_132_ap_start),
    .ap_done(grp_example_Pipeline_4_fu_132_ap_done),
    .ap_idle(grp_example_Pipeline_4_fu_132_ap_idle),
    .ap_ready(grp_example_Pipeline_4_fu_132_ap_ready),
    .m_axi_a_AWVALID(grp_example_Pipeline_4_fu_132_m_axi_a_AWVALID),
    .m_axi_a_AWREADY(a_AWREADY),
    .m_axi_a_AWADDR(grp_example_Pipeline_4_fu_132_m_axi_a_AWADDR),
    .m_axi_a_AWID(grp_example_Pipeline_4_fu_132_m_axi_a_AWID),
    .m_axi_a_AWLEN(grp_example_Pipeline_4_fu_132_m_axi_a_AWLEN),
    .m_axi_a_AWSIZE(grp_example_Pipeline_4_fu_132_m_axi_a_AWSIZE),
    .m_axi_a_AWBURST(grp_example_Pipeline_4_fu_132_m_axi_a_AWBURST),
    .m_axi_a_AWLOCK(grp_example_Pipeline_4_fu_132_m_axi_a_AWLOCK),
    .m_axi_a_AWCACHE(grp_example_Pipeline_4_fu_132_m_axi_a_AWCACHE),
    .m_axi_a_AWPROT(grp_example_Pipeline_4_fu_132_m_axi_a_AWPROT),
    .m_axi_a_AWQOS(grp_example_Pipeline_4_fu_132_m_axi_a_AWQOS),
    .m_axi_a_AWREGION(grp_example_Pipeline_4_fu_132_m_axi_a_AWREGION),
    .m_axi_a_AWUSER(grp_example_Pipeline_4_fu_132_m_axi_a_AWUSER),
    .m_axi_a_WVALID(grp_example_Pipeline_4_fu_132_m_axi_a_WVALID),
    .m_axi_a_WREADY(a_WREADY),
    .m_axi_a_WDATA(grp_example_Pipeline_4_fu_132_m_axi_a_WDATA),
    .m_axi_a_WSTRB(grp_example_Pipeline_4_fu_132_m_axi_a_WSTRB),
    .m_axi_a_WLAST(grp_example_Pipeline_4_fu_132_m_axi_a_WLAST),
    .m_axi_a_WID(grp_example_Pipeline_4_fu_132_m_axi_a_WID),
    .m_axi_a_WUSER(grp_example_Pipeline_4_fu_132_m_axi_a_WUSER),
    .m_axi_a_ARVALID(grp_example_Pipeline_4_fu_132_m_axi_a_ARVALID),
    .m_axi_a_ARREADY(1'b0),
    .m_axi_a_ARADDR(grp_example_Pipeline_4_fu_132_m_axi_a_ARADDR),
    .m_axi_a_ARID(grp_example_Pipeline_4_fu_132_m_axi_a_ARID),
    .m_axi_a_ARLEN(grp_example_Pipeline_4_fu_132_m_axi_a_ARLEN),
    .m_axi_a_ARSIZE(grp_example_Pipeline_4_fu_132_m_axi_a_ARSIZE),
    .m_axi_a_ARBURST(grp_example_Pipeline_4_fu_132_m_axi_a_ARBURST),
    .m_axi_a_ARLOCK(grp_example_Pipeline_4_fu_132_m_axi_a_ARLOCK),
    .m_axi_a_ARCACHE(grp_example_Pipeline_4_fu_132_m_axi_a_ARCACHE),
    .m_axi_a_ARPROT(grp_example_Pipeline_4_fu_132_m_axi_a_ARPROT),
    .m_axi_a_ARQOS(grp_example_Pipeline_4_fu_132_m_axi_a_ARQOS),
    .m_axi_a_ARREGION(grp_example_Pipeline_4_fu_132_m_axi_a_ARREGION),
    .m_axi_a_ARUSER(grp_example_Pipeline_4_fu_132_m_axi_a_ARUSER),
    .m_axi_a_RVALID(1'b0),
    .m_axi_a_RREADY(grp_example_Pipeline_4_fu_132_m_axi_a_RREADY),
    .m_axi_a_RDATA(32'd0),
    .m_axi_a_RLAST(1'b0),
    .m_axi_a_RID(1'd0),
    .m_axi_a_RFIFONUM(9'd0),
    .m_axi_a_RUSER(1'd0),
    .m_axi_a_RRESP(2'd0),
    .m_axi_a_BVALID(a_BVALID),
    .m_axi_a_BREADY(grp_example_Pipeline_4_fu_132_m_axi_a_BREADY),
    .m_axi_a_BRESP(2'd0),
    .m_axi_a_BID(1'd0),
    .m_axi_a_BUSER(1'd0),
    .sext_ln44(trunc_ln_reg_188),
    .buffa_address0(grp_example_Pipeline_4_fu_132_buffa_address0),
    .buffa_ce0(grp_example_Pipeline_4_fu_132_buffa_ce0),
    .buffa_q0(buffa_q0)
);

example_example_Pipeline_5 grp_example_Pipeline_5_fu_140(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_example_Pipeline_5_fu_140_ap_start),
    .ap_done(grp_example_Pipeline_5_fu_140_ap_done),
    .ap_idle(grp_example_Pipeline_5_fu_140_ap_idle),
    .ap_ready(grp_example_Pipeline_5_fu_140_ap_ready),
    .m_axi_b_AWVALID(grp_example_Pipeline_5_fu_140_m_axi_b_AWVALID),
    .m_axi_b_AWREADY(b_AWREADY),
    .m_axi_b_AWADDR(grp_example_Pipeline_5_fu_140_m_axi_b_AWADDR),
    .m_axi_b_AWID(grp_example_Pipeline_5_fu_140_m_axi_b_AWID),
    .m_axi_b_AWLEN(grp_example_Pipeline_5_fu_140_m_axi_b_AWLEN),
    .m_axi_b_AWSIZE(grp_example_Pipeline_5_fu_140_m_axi_b_AWSIZE),
    .m_axi_b_AWBURST(grp_example_Pipeline_5_fu_140_m_axi_b_AWBURST),
    .m_axi_b_AWLOCK(grp_example_Pipeline_5_fu_140_m_axi_b_AWLOCK),
    .m_axi_b_AWCACHE(grp_example_Pipeline_5_fu_140_m_axi_b_AWCACHE),
    .m_axi_b_AWPROT(grp_example_Pipeline_5_fu_140_m_axi_b_AWPROT),
    .m_axi_b_AWQOS(grp_example_Pipeline_5_fu_140_m_axi_b_AWQOS),
    .m_axi_b_AWREGION(grp_example_Pipeline_5_fu_140_m_axi_b_AWREGION),
    .m_axi_b_AWUSER(grp_example_Pipeline_5_fu_140_m_axi_b_AWUSER),
    .m_axi_b_WVALID(grp_example_Pipeline_5_fu_140_m_axi_b_WVALID),
    .m_axi_b_WREADY(b_WREADY),
    .m_axi_b_WDATA(grp_example_Pipeline_5_fu_140_m_axi_b_WDATA),
    .m_axi_b_WSTRB(grp_example_Pipeline_5_fu_140_m_axi_b_WSTRB),
    .m_axi_b_WLAST(grp_example_Pipeline_5_fu_140_m_axi_b_WLAST),
    .m_axi_b_WID(grp_example_Pipeline_5_fu_140_m_axi_b_WID),
    .m_axi_b_WUSER(grp_example_Pipeline_5_fu_140_m_axi_b_WUSER),
    .m_axi_b_ARVALID(grp_example_Pipeline_5_fu_140_m_axi_b_ARVALID),
    .m_axi_b_ARREADY(1'b0),
    .m_axi_b_ARADDR(grp_example_Pipeline_5_fu_140_m_axi_b_ARADDR),
    .m_axi_b_ARID(grp_example_Pipeline_5_fu_140_m_axi_b_ARID),
    .m_axi_b_ARLEN(grp_example_Pipeline_5_fu_140_m_axi_b_ARLEN),
    .m_axi_b_ARSIZE(grp_example_Pipeline_5_fu_140_m_axi_b_ARSIZE),
    .m_axi_b_ARBURST(grp_example_Pipeline_5_fu_140_m_axi_b_ARBURST),
    .m_axi_b_ARLOCK(grp_example_Pipeline_5_fu_140_m_axi_b_ARLOCK),
    .m_axi_b_ARCACHE(grp_example_Pipeline_5_fu_140_m_axi_b_ARCACHE),
    .m_axi_b_ARPROT(grp_example_Pipeline_5_fu_140_m_axi_b_ARPROT),
    .m_axi_b_ARQOS(grp_example_Pipeline_5_fu_140_m_axi_b_ARQOS),
    .m_axi_b_ARREGION(grp_example_Pipeline_5_fu_140_m_axi_b_ARREGION),
    .m_axi_b_ARUSER(grp_example_Pipeline_5_fu_140_m_axi_b_ARUSER),
    .m_axi_b_RVALID(rvalid),
    .m_axi_b_RREADY(grp_example_Pipeline_5_fu_140_m_axi_b_RREADY),
    .m_axi_b_RDATA(32'd0),
    .m_axi_b_RLAST(1'b0),
    .m_axi_b_RID(1'd0),
    .m_axi_b_RFIFONUM(9'd0),
    .m_axi_b_RUSER(1'd0),
    .m_axi_b_RRESP(2'd0),
    .m_axi_b_BVALID(b_BVALID),
    .m_axi_b_BREADY(grp_example_Pipeline_5_fu_140_m_axi_b_BREADY),
    .m_axi_b_BRESP(2'd0),
    .m_axi_b_BID(1'd0),
    .m_axi_b_BUSER(1'd0),
    .sext_ln48(trunc_ln1_reg_195),
    .buffb_address0(grp_example_Pipeline_5_fu_140_buffb_address0),
    .buffb_ce0(grp_example_Pipeline_5_fu_140_buffb_ce0),
    .buffb_q0(buffb_q0)
);

example_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .a_offset(a_offset),
    .b_offset(b_offset)
);

example_a_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_A_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_A_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_A_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_A_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_A_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_A_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_A_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_A_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_A_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_A_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_A_CACHE_VALUE ),
    .USER_DW( 32 ),
    .USER_AW( 64 ))
a_m_axi_U(
    .AWVALID(m_axi_a_AWVALID),
    .AWREADY(m_axi_a_AWREADY),
    .AWADDR(m_axi_a_AWADDR),
    .AWID(m_axi_a_AWID),
    .AWLEN(m_axi_a_AWLEN),
    .AWSIZE(m_axi_a_AWSIZE),
    .AWBURST(m_axi_a_AWBURST),
    .AWLOCK(m_axi_a_AWLOCK),
    .AWCACHE(m_axi_a_AWCACHE),
    .AWPROT(m_axi_a_AWPROT),
    .AWQOS(m_axi_a_AWQOS),
    .AWREGION(m_axi_a_AWREGION),
    .AWUSER(m_axi_a_AWUSER),
    .WVALID(m_axi_a_WVALID),
    .WREADY(m_axi_a_WREADY),
    .WDATA(m_axi_a_WDATA),
    .WSTRB(m_axi_a_WSTRB),
    .WLAST(m_axi_a_WLAST),
    .WID(m_axi_a_WID),
    .WUSER(m_axi_a_WUSER),
    .ARVALID(m_axi_a_ARVALID),
    .ARREADY(m_axi_a_ARREADY),
    .ARADDR(m_axi_a_ARADDR),
    .ARID(m_axi_a_ARID),
    .ARLEN(m_axi_a_ARLEN),
    .ARSIZE(m_axi_a_ARSIZE),
    .ARBURST(m_axi_a_ARBURST),
    .ARLOCK(m_axi_a_ARLOCK),
    .ARCACHE(m_axi_a_ARCACHE),
    .ARPROT(m_axi_a_ARPROT),
    .ARQOS(m_axi_a_ARQOS),
    .ARREGION(m_axi_a_ARREGION),
    .ARUSER(m_axi_a_ARUSER),
    .RVALID(m_axi_a_RVALID),
    .RREADY(m_axi_a_RREADY),
    .RDATA(m_axi_a_RDATA),
    .RLAST(m_axi_a_RLAST),
    .RID(m_axi_a_RID),
    .RUSER(m_axi_a_RUSER),
    .RRESP(m_axi_a_RRESP),
    .BVALID(m_axi_a_BVALID),
    .BREADY(m_axi_a_BREADY),
    .BRESP(m_axi_a_BRESP),
    .BID(m_axi_a_BID),
    .BUSER(m_axi_a_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(a_ARVALID),
    .I_ARREADY(a_ARREADY),
    .I_ARADDR(a_ARADDR),
    .I_ARLEN(a_ARLEN),
    .I_RVALID(a_RVALID),
    .I_RREADY(a_RREADY),
    .I_RDATA(a_RDATA),
    .I_RFIFONUM(a_RFIFONUM),
    .I_AWVALID(a_AWVALID),
    .I_AWREADY(a_AWREADY),
    .I_AWADDR(a_AWADDR),
    .I_AWLEN(a_AWLEN),
    .I_WVALID(a_WVALID),
    .I_WREADY(a_WREADY),
    .I_WDATA(grp_example_Pipeline_4_fu_132_m_axi_a_WDATA),
    .I_WSTRB(grp_example_Pipeline_4_fu_132_m_axi_a_WSTRB),
    .I_BVALID(a_BVALID),
    .I_BREADY(a_BREADY)
);

example_b_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_B_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_B_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_B_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_B_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_B_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_B_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_B_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_B_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_B_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_B_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_B_CACHE_VALUE ),
    .USER_DW( 32 ),
    .USER_AW( 64 ))
b_m_axi_U(
    .AWVALID(m_axi_b_AWVALID),
    .AWREADY(m_axi_b_AWREADY),
    .AWADDR(m_axi_b_AWADDR),
    .AWID(m_axi_b_AWID),
    .AWLEN(m_axi_b_AWLEN),
    .AWSIZE(m_axi_b_AWSIZE),
    .AWBURST(m_axi_b_AWBURST),
    .AWLOCK(m_axi_b_AWLOCK),
    .AWCACHE(m_axi_b_AWCACHE),
    .AWPROT(m_axi_b_AWPROT),
    .AWQOS(m_axi_b_AWQOS),
    .AWREGION(m_axi_b_AWREGION),
    .AWUSER(m_axi_b_AWUSER),
    .WVALID(m_axi_b_WVALID),
    .WREADY(m_axi_b_WREADY),
    .WDATA(m_axi_b_WDATA),
    .WSTRB(m_axi_b_WSTRB),
    .WLAST(m_axi_b_WLAST),
    .WID(m_axi_b_WID),
    .WUSER(m_axi_b_WUSER),
    .ARVALID(m_axi_b_ARVALID),
    .ARREADY(m_axi_b_ARREADY),
    .ARADDR(m_axi_b_ARADDR),
    .ARID(m_axi_b_ARID),
    .ARLEN(m_axi_b_ARLEN),
    .ARSIZE(m_axi_b_ARSIZE),
    .ARBURST(m_axi_b_ARBURST),
    .ARLOCK(m_axi_b_ARLOCK),
    .ARCACHE(m_axi_b_ARCACHE),
    .ARPROT(m_axi_b_ARPROT),
    .ARQOS(m_axi_b_ARQOS),
    .ARREGION(m_axi_b_ARREGION),
    .ARUSER(m_axi_b_ARUSER),
    .RVALID(rvalid),
    .RREADY(m_axi_b_RREADY),
    .RDATA(m_axi_b_RDATA),
    .RLAST(m_axi_b_RLAST),
    .RID(m_axi_b_RID),
    .RUSER(m_axi_b_RUSER),
    .RRESP(m_axi_b_RRESP),
    .BVALID(m_axi_b_BVALID),
    .BREADY(m_axi_b_BREADY),
    .BRESP(m_axi_b_BRESP),
    .BID(m_axi_b_BID),
    .BUSER(m_axi_b_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(b_ARVALID),
    .I_ARREADY(b_ARREADY),
    .I_ARADDR(b_ARADDR),
    .I_ARLEN(b_ARLEN),
    .I_RVALID(b_RVALID),
    .I_RREADY(b_RREADY),
    .I_RDATA(b_RDATA),
    .I_RFIFONUM(b_RFIFONUM),
    .I_AWVALID(b_AWVALID),
    .I_AWREADY(b_AWREADY),
    .I_AWADDR(b_AWADDR),
    .I_AWLEN(b_AWLEN),
    .I_WVALID(b_WVALID),
    .I_WREADY(b_WREADY),
    .I_WDATA(grp_example_Pipeline_5_fu_140_m_axi_b_WDATA),
    .I_WSTRB(grp_example_Pipeline_5_fu_140_m_axi_b_WSTRB),
    .I_BVALID(b_BVALID),
    .I_BREADY(b_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_example_Pipeline_1_fu_110_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_example_Pipeline_1_fu_110_ap_start_reg <= 1'b1;
        end else if ((grp_example_Pipeline_1_fu_110_ap_ready == 1'b1)) begin
            grp_example_Pipeline_1_fu_110_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_example_Pipeline_2_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_example_Pipeline_2_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_example_Pipeline_2_fu_118_ap_ready == 1'b1)) begin
            grp_example_Pipeline_2_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_example_Pipeline_4_fu_132_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_example_Pipeline_4_fu_132_ap_start_reg <= 1'b1;
        end else if ((grp_example_Pipeline_4_fu_132_ap_ready == 1'b1)) begin
            grp_example_Pipeline_4_fu_132_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_example_Pipeline_5_fu_140_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_example_Pipeline_5_fu_140_ap_start_reg <= 1'b1;
        end else if ((grp_example_Pipeline_5_fu_140_ap_ready == 1'b1)) begin
            grp_example_Pipeline_5_fu_140_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start_reg <= 1'b1;
        end else if ((grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_ready == 1'b1)) begin
            grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        a_addr_reg_202 <= sext_ln44_fu_168_p1;
        b_addr_reg_207 <= sext_ln48_fu_178_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln1_reg_195 <= {{b_offset[63:2]}};
        trunc_ln_reg_188 <= {{a_offset[63:2]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        a_ARADDR = sext_ln44_fu_168_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        a_ARADDR = grp_example_Pipeline_1_fu_110_m_axi_a_ARADDR;
    end else begin
        a_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        a_ARLEN = 32'd50;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        a_ARLEN = grp_example_Pipeline_1_fu_110_m_axi_a_ARLEN;
    end else begin
        a_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        a_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        a_ARVALID = grp_example_Pipeline_1_fu_110_m_axi_a_ARVALID;
    end else begin
        a_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
        a_AWADDR = a_addr_reg_202;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        a_AWADDR = grp_example_Pipeline_4_fu_132_m_axi_a_AWADDR;
    end else begin
        a_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
        a_AWLEN = 32'd50;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        a_AWLEN = grp_example_Pipeline_4_fu_132_m_axi_a_AWLEN;
    end else begin
        a_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
        a_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        a_AWVALID = grp_example_Pipeline_4_fu_132_m_axi_a_AWVALID;
    end else begin
        a_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((b_BVALID == 1'b0) | (1'b0 == a_BVALID)) & (1'b1 == ap_CS_fsm_state19))) begin
        a_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        a_BREADY = grp_example_Pipeline_4_fu_132_m_axi_a_BREADY;
    end else begin
        a_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        a_RREADY = grp_example_Pipeline_1_fu_110_m_axi_a_RREADY;
    end else begin
        a_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        a_WVALID = grp_example_Pipeline_4_fu_132_m_axi_a_WVALID;
    end else begin
        a_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        a_blk_n_AR = m_axi_a_ARREADY;
    end else begin
        a_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        a_blk_n_AW = m_axi_a_AWREADY;
    end else begin
        a_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        a_blk_n_B = m_axi_a_BVALID;
    end else begin
        a_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state11_io)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state14_on_subcall_done)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if (((b_BVALID == 1'b0) | (1'b0 == a_BVALID))) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_io)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((b_BVALID == 1'b0) | (1'b0 == a_BVALID)) & (1'b1 == ap_CS_fsm_state19))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((b_BVALID == 1'b0) | (1'b0 == a_BVALID)) & (1'b1 == ap_CS_fsm_state19))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        b_ARADDR = sext_ln48_fu_178_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        b_ARADDR = grp_example_Pipeline_2_fu_118_m_axi_b_ARADDR;
    end else begin
        b_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        b_ARLEN = 32'd50;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        b_ARLEN = grp_example_Pipeline_2_fu_118_m_axi_b_ARLEN;
    end else begin
        b_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
        b_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        b_ARVALID = grp_example_Pipeline_2_fu_118_m_axi_b_ARVALID;
    end else begin
        b_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
        b_AWADDR = b_addr_reg_207;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        b_AWADDR = grp_example_Pipeline_5_fu_140_m_axi_b_AWADDR;
    end else begin
        b_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
        b_AWLEN = 32'd50;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        b_AWLEN = grp_example_Pipeline_5_fu_140_m_axi_b_AWLEN;
    end else begin
        b_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
        b_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        b_AWVALID = grp_example_Pipeline_5_fu_140_m_axi_b_AWVALID;
    end else begin
        b_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((b_BVALID == 1'b0) | (1'b0 == a_BVALID)) & (1'b1 == ap_CS_fsm_state19))) begin
        b_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        b_BREADY = grp_example_Pipeline_5_fu_140_m_axi_b_BREADY;
    end else begin
        b_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        b_RREADY = grp_example_Pipeline_2_fu_118_m_axi_b_RREADY;
    end else begin
        b_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        b_WVALID = grp_example_Pipeline_5_fu_140_m_axi_b_WVALID;
    end else begin
        b_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b_blk_n_AR = m_axi_b_ARREADY;
    end else begin
        b_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        b_blk_n_AW = m_axi_b_AWREADY;
    end else begin
        b_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        b_blk_n_B = m_axi_b_BVALID;
    end else begin
        b_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buffa_address0 = grp_example_Pipeline_4_fu_132_buffa_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buffa_address0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffa_address0 = grp_example_Pipeline_1_fu_110_buffa_address0;
    end else begin
        buffa_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buffa_ce0 = grp_example_Pipeline_4_fu_132_buffa_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buffa_ce0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffa_ce0 = grp_example_Pipeline_1_fu_110_buffa_ce0;
    end else begin
        buffa_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buffa_ce1 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_ce1;
    end else begin
        buffa_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buffa_d0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffa_d0 = grp_example_Pipeline_1_fu_110_buffa_d0;
    end else begin
        buffa_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buffa_we0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffa_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffa_we0 = grp_example_Pipeline_1_fu_110_buffa_we0;
    end else begin
        buffa_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buffb_address0 = grp_example_Pipeline_5_fu_140_buffb_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buffb_address0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffb_address0 = grp_example_Pipeline_2_fu_118_buffb_address0;
    end else begin
        buffb_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buffb_ce0 = grp_example_Pipeline_5_fu_140_buffb_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buffb_ce0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffb_ce0 = grp_example_Pipeline_2_fu_118_buffb_ce0;
    end else begin
        buffb_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buffb_ce1 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_ce1;
    end else begin
        buffb_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buffb_d0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffb_d0 = grp_example_Pipeline_2_fu_118_buffb_d0;
    end else begin
        buffb_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buffb_we0 = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_buffb_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buffb_we0 = grp_example_Pipeline_2_fu_118_buffb_we0;
    end else begin
        buffb_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if ((~((b_BVALID == 1'b0) | (1'b0 == a_BVALID)) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((grp_example_Pipeline_2_fu_118_ap_done == 1'b0) | (grp_example_Pipeline_1_fu_110_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state11_io = ((b_AWREADY == 1'b0) | (1'b0 == a_AWREADY));
end

always @ (*) begin
    ap_block_state14_on_subcall_done = ((grp_example_Pipeline_5_fu_140_ap_done == 1'b0) | (grp_example_Pipeline_4_fu_132_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state19 = ((b_BVALID == 1'b0) | (1'b0 == a_BVALID));
end

always @ (*) begin
    ap_block_state2_io = ((b_ARREADY == 1'b0) | (1'b0 == a_ARREADY));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_example_Pipeline_1_fu_110_ap_start = grp_example_Pipeline_1_fu_110_ap_start_reg;

assign grp_example_Pipeline_2_fu_118_ap_start = grp_example_Pipeline_2_fu_118_ap_start_reg;

assign grp_example_Pipeline_4_fu_132_ap_start = grp_example_Pipeline_4_fu_132_ap_start_reg;

assign grp_example_Pipeline_5_fu_140_ap_start = grp_example_Pipeline_5_fu_140_ap_start_reg;

assign grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start = grp_example_Pipeline_VITIS_LOOP_57_1_fu_126_ap_start_reg;

assign sext_ln44_fu_168_p1 = $signed(trunc_ln_reg_188);

assign sext_ln48_fu_178_p1 = $signed(trunc_ln1_reg_195);

endmodule //example
